[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
scripts = { "decompiler-explorer" = "decompiler_explorer:main" }
name = "decompiler-explorer"
description = "Decompiler explorer"
version = "1.0.0"
dependencies = ["watchfiles"]
